// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson31477e3DecodeMiguModel(in *jlexer.Lexer, out *Music) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "title":
			out.Title = string(in.String())
		case "linkUrl":
			out.LinkUrl = string(in.String())
		case "quality":
			out.Quality = string(in.String())
		case "singer":
			out.Singer = string(in.String())
		case "album":
			out.Album = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson31477e3EncodeMiguModel(out *jwriter.Writer, in Music) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix[1:])
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"linkUrl\":"
		out.RawString(prefix)
		out.String(string(in.LinkUrl))
	}
	{
		const prefix string = ",\"quality\":"
		out.RawString(prefix)
		out.String(string(in.Quality))
	}
	{
		const prefix string = ",\"singer\":"
		out.RawString(prefix)
		out.String(string(in.Singer))
	}
	{
		const prefix string = ",\"album\":"
		out.RawString(prefix)
		out.String(string(in.Album))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Music) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson31477e3EncodeMiguModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Music) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson31477e3EncodeMiguModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Music) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson31477e3DecodeMiguModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Music) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson31477e3DecodeMiguModel(l, v)
}
